name: go-release
on:
  release:
    types: [published]
jobs:
  build:
    name: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: build
        run: make cli
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/flux-status-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
